name: CI Workflow

on:
    pull_request:
        branches:
            - main
    release:
        types: [published]

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.x' # Adjust this version if needed
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry tox
                  poetry install --with dev
            - name: Run Tox
              run: tox
            - name: Check code formatting with Black
              run: |
                  poetry run black --check .
    deploy:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'release'
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.x'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build
            - name: Build package
              run: python -m build
            - name: Publish package
              uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
